services:
  build:
    build:
      context: ./
      dockerfile: containers/build.dockerfile
    volumes:
      - ./out:/build/out:rw
      - ./kernel:/build/kernel:ro
      - ./userspace:/build/userspace:ro
      - target-kernel:/build/kernel/target:rw
      - target-userspace:/build/userspace/target:rw
      - registry:/usr/local/cargo/registry:rw
      - ./.cargo:/build/.cargo:ro
      - ./config:/build/config:ro
      - ./rustfmt.toml:/build/rustfmt.toml:ro
      - ./rust-toolchain:/build/rust-toolchain:ro
  debug:
    build:
      context: ./
      dockerfile: containers/debug.dockerfile
    env_file:
      - ./config/env/debug.env
    network_mode: host
    volumes:
      - registry:/usr/local/cargo/registry:rw
      - ./out/helium.iso:/vm/helium.iso:rw
      - ./out/kernel.dbg:/vm/kernel.dbg:ro
      - ./config/tmux.conf:/root/.tmux.conf:ro
      - ./config/gdbinit:/root/.gdbinit:ro
      - ./kernel:/build/kernel:ro
      - ./userspace:/build/userspace:ro
volumes:
  target-kernel:
  target-userspace:
  registry:
