services:
  build:
    build:
      context: ./
      dockerfile: containers/build.dockerfile
    volumes:
      - ./out:/build/out:rw
      - ./src:/build/src:ro
      - target:/build/target:rw
      - registry:/usr/local/cargo/registry:rw
      - ./.cargo:/build/.cargo:ro
      - ./config:/build/config:ro
      - ./Cargo.toml:/build/Cargo.toml:ro
      - ./Cargo.lock:/build/Cargo.lock:rw
      - ./rustfmt.toml:/build/rustfmt.toml:ro
      - ./rust-toolchain:/build/rust-toolchain:ro
  debug:
    build:
      context: ./
      dockerfile: containers/debug.dockerfile
    environment:
      MEMORY: 512M
      CPU: 4
    network_mode: host
    volumes:
      - ./out/helium.img:/vm/helium.img:rw
      - ./out/helium.dbg:/vm/helium.dbg:ro
      - ./config/gdbinit:/root/.gdbinit:ro
      - ./config/tmux.conf:/root/.tmux.conf:ro
      - ./src:/build/src:ro

volumes:
  target:
  registry:

