services:
  build:
    build:
      context: ./
      dockerfile: containers/build.dockerfile
    volumes:
      - ./out:/build/out:rw
      - ./src:/build/src:ro
      - target:/build/target:rw
      - ./.cargo:/build/.cargo:ro
      - ./config:/build/config:ro
      - ./Cargo.toml:/build/Cargo.toml:ro
      - ./Cargo.lock:/build/Cargo.lock:rw
      - ./rustfmt.toml:/build/rustfmt.toml:ro
      - ./rust-toolchain:/build/rust-toolchain:ro
  qemu:
    build:
      context: ./
      dockerfile: containers/qemu.dockerfile
    environment:
      MEMORY: 512M
      CPU: 1
    network_mode: host
    volumes:
      - ./out/helium.img:/vm/helium.img:rw

volumes:
  target:

