name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: docker compose run --build build
    - name: Upload ISO
      uses: actions/upload-artifact@v2
      with:
        name: helium.img
        path: out
