name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.2
    - name: Build
      run: docker compose run --build build
    - name: Upload ISO
      uses: actions/upload-artifact@v4.3.1
      with:
        name: Helium
        path: out
